### ISSUE TITLE
error when import snack project from github

### ISSUE THREAD

**Issue by saeedjafary** [expo/snack#19] opened 2020-03-14 06:53 UTC
when i try to use Import git repository in snack to edit my react native project this error is displayed : An error occurred during import. This could be because the data provided was invalid, or because the repository referenced is not a properly formatted Expo project.

my github link is : https://github.com/saeedjafary/SarvShop

I am seeing this error recently. there was no problem before

**Comment by IjzerenHein** [comment] 2021-02-08 10:54
Duplicate of #54

**Closed by IjzerenHein** 2021-02-08 10:54 UTC
Labels: bug, snackager

**Comment by ashim1588** [comment] 2023-12-12 17:28
Same Issue here
