### ISSUE TITLE
updating state inside useEffect freezes the whole website

### ISSUE THREAD

**Issue by hetanthakkar1** [expo/snack#153] opened 2021-05-30 17:09 UTC
### Summary

Expected behaviour: Snack should recognize this pattern beforehand of updating state inside useEffect and prevent user doing that

Current behaviour: When we update state inside useEffect browser freezes

I want to work on this problem can I?

### What platform(s) does this occur on?

Android

### Reproducible demo or steps to reproduce from a blank project

1. Make a state in snack react native
2. update that in useEffect hook
3. You will see website freezing in few seconds/minutes

**Comment by byCedric** [comment] 2021-06-01 17:06
Hi @hetanthakkar1! I'm not sure how you update the state in an effect. One thing to notice is that this is really prone to an infinite loop or state update if you aren't careful. This might be the cause of the freeze, if you have a snippet that you tried that would help to validate that 😄 

And feel free to create a PR, I'm not sure how we would detect an infinite state update though.

**Comment by IjzerenHein** [comment] 2021-06-17 09:17
For reference and testing, I created this Snack that runs an infinite `useEffect` loop. This does not appear to cause the browser to hang (tested with Chrome on Mac): https://snack.expo.io/AD6PkZjmZ

Snack actually provides a warning about the incorrect use of `useEffect` here, as shown below:
![image](https://user-images.githubusercontent.com/6184593/122368206-6a76a280-cf5d-11eb-88d5-d214e00426c1.png)

Closing this as this appears React related and not Snack related.
Feel free to reopen with additional details in and a reproduction case.

**Closed by IjzerenHein** 2021-06-17 09:17 UTC
